# Copyright 2025 Sony Group Corporation.
# All rights reserved.
#
# Licenced under the License reported at
#
#     https://github.com/LTTM/MultimodalStudio/LICENSE.txt (the "License").
#
# See the License for the specific language governing permissions and limitations under the License.
#
# Author: Federico Lincetto, Ph.D. Student at the University of Padova

---

method: grid_raw_grid_bg_unbalanced

n_gpu: 1
mixed_precision: True
matmul_precision: high
max_num_iterations: 100000
steps_per_eval_batch: 200
steps_per_eval_image: 5000
steps_per_eval_all_images: 50000
steps_per_export_mesh: 50000
steps_per_export_poses: 10000
steps_per_save: 5000

pipeline:
  evaluator:
    eval_num_rays_per_chunk: 2048
    rendering_scale: 0.25
    export_mesh: True
    mesh_extractor:
      gt_scale: False
    export_poses: True
    pose_extractor:
      gt_scale: False
  
  datamanager:
    modalities:
      - rgb
      - polarization

    eval_image_indices_per_modality:
      rgb: [9, 19, 29, 39, 49]
      polarization: [9, 19, 29, 39, 49]

    skip_image_indices_per_modality:
      polarization: [0, 1, 2, 3, 5, 7, 8, 10, 11, 13, 15, 16, 17, 18, 20, 21, 23, 24, 26, 28, 30, 31, 32, 33, 35, 36, 37, 38, 40, 42, 43, 45, 46, 47, 48]
  
    camera_optimizer:
      mode: 'SO3xR3'
      shared_optimization: True
      modalities_to_optimize:
        rgb: True
        polarization: True

    pixel_sampler:
      num_rays_per_modality: 2048

  model:
    ray_sampler:
      num_samples: 32
      num_samples_importance: 32

    background_ray_sampler:
      num_samples: 16

    surface_model:
      use_numerical_gradients: True
      numerical_gradient_taps: 4
      surface_field:
        field:
          feature_grid:
            encoding:
              max_res: 1024
            coarse_to_fine: True
            radius: 1.0
          mlp_head:
            hidden_dim: 256
            geometric_init: True
            weight_norm: True
            geometric_init_bias: 0.4
        use_position_encoding: True

    radiance_model:
      radiance_field:
        base_field:
          feature_grid:
            encoding:
              max_res: 1024
            coarse_to_fine: True
            radius: 1.0
          mlp_head:
            hidden_dim: 256
            weight_norm: True
      use_reflection_direction: False
      use_n_dot_v: True

    background_model:
      background_field:
        head_field:
          hidden_dim: 256
          weight_norm: True

logging:
  steps_per_log: 100
  steps_per_flush_buffer: 100

...
